name: "poetry"
port: 9501
domain: "localhost"
logsAddress: "./logs/"

mysql:
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: poetry # 数据库名称
  username: root # 用户名
  password:  # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

 
redis:
 host: "112.124.10.134"
 port: 6379


jwt:
  key: "EYsnfKMf5XWk87LASEs28Dj5ZqGkSerH"
